# Generated by Django 2.2.12 on 2021-11-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ball',
            name='xz',
            field=models.IntegerField(default=1),
        ),
    ]
