# Generated by Django 2.2.12 on 2021-11-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
