# Generated by Django 2.2.12 on 2021-11-22 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20211120_1658'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
