# Generated by Django 2.2.12 on 2021-11-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=11, verbose_name='name')),
                ('age', models.IntegerField(default=1, verbose_name='age')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='email')),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=64, unique=True, verbose_name='name')),
                ('pub', models.CharField(default='', max_length=100, verbose_name='pub')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='price')),
                ('info', models.CharField(default='', max_length=100, verbose_name='info')),
                ('market_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='market_price')),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
