# Generated by Django 2.2.12 on 2021-11-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20211117_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='info',
            field=models.CharField(default='', max_length=100, verbose_name='infos'),
        ),
    ]
