# Generated by Django 2.2.12 on 2021-11-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20211117_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='test',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='test'),
        ),
    ]
