# Generated by Django 2.2.12 on 2021-11-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_book_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='info',
            field=models.CharField(db_column='info_test', default='', max_length=100, verbose_name='info'),
        ),
    ]
