# Generated by Django 2.2.12 on 2021-11-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_book_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='', max_length=64, unique=True, verbose_name='书名'),
        ),
    ]
