# Generated by Django 2.2.12 on 2021-11-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_auto_20211118_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='test',
            field=models.CharField(db_column='测试用的', default='', max_length=50, verbose_name='测试'),
        ),
    ]
